### ISSUE TITLE
若验证不通过，希望返回json类型的数据，怎么处理

### ISSUE THREAD

**Issue by fernando1987** [devefx/validator-web#1]
java.lang.RuntimeException: Could not extract response: no suitable HttpMessageReader found for response type [interface org.devefx.validator.util.MultiValueMap] and content type [application/json]
	at org.devefx.validator.http.extract.HttpMessageReaderExtractor.extractData(HttpMessageReaderExtractor.java:70) ~[validator-web-1.0.0-alphal.jar:?]
	at org.devefx.validator.internal.engine.ValidatorImpl.createValueContext(ValidatorImpl.java:131) ~[validator-web-1.0.0-alphal.jar:?]
	at org.devefx.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:79) ~[validator-web-1.0.0-alphal.jar:?]
	at org.devefx.validator.external.spring.mvc.SpringValidatorInterceptor.preHandle(SpringValidatorInterceptor.java:53) ~[validator-web-1.0.0-alphal.jar:?]

**Comment by devefx** [comment]
## 设置错误输出风格

```java
<!-- 创建Validator配置 -->
<bean id="validatorConfig" class="org.devefx.validator.ValidatorConfig">
    <property name="invalidHandler">
        <bean class="org.devefx.validator.internal.engine.DefaultInvalidHandler">
            <!-- 设置输出风格为JSON -->
            <property name="outputStyle" value="JSON"/>
        </bean>
    </property>
</bean>
```

## 支持post数据为xml/json类型
- 必须指定requestType（请求的类型）
- 请求的Header中必须设置Content-Type（默认提供application/xml与application/json）
> 如果Content-Type为application/xml，请提交json数据
> 更多自定义类型去参考[HttpMessageReader.java](https://github.com/devefx/validator-web/blob/master/validator-web/src/main/java/org/devefx/validator/http/reader/HttpMessageReader.java)
```java
@Valid(value=MyValidation.class, requestType=MyModel.class)
@RequestMapping("/")
public void render() {
 // 验证通过后，获取请求模型
 MyModel myModel = (MyModel) ThreadContext.getModel();
}
```

**Comment by fernando1987** [comment]
谢谢，再请教一个问题 
requestType 有没有固定格式？
以前使用hibernate validator 时，验证失败会抛出BindException由异常处理器统一处理。
这一块已经相当完善，这块可以统一处理吗？

**Comment by devefx** [comment]
验证失败由[InvalidHandler](https://github.com/devefx/validator-web/blob/master/validator-web/src/main/java/org/devefx/validator/InvalidHandler.java)处理，ValidatorConfig.setInvalidHandler设置统一处理器，也可以在具体的Validation使用ValidationContext.setInvalidHandler进行特殊处理
请参考配置：https://github.com/devefx/validator-web/blob/master/docs/springmvc/getting-started.md
